name: CMake

on:
  push:

jobs:
  lockfree_stack_counting:
    uses: ./.github/workflows/stack_counting.yaml
  lockfree_stack_hazard:
    uses: ./.github/workflows/stack_hazard_ptr.yaml
#  sync:
#    uses: ./.github/workflows/sync.yaml
  spinlock:
    uses: ./.github/workflows/spinlock.yaml
  mutex:
    uses: ./.github/workflows/mutex.yaml